// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

func (d *CompanyPatch) MergeToType() Company {
	var tmpID int
	if d.ID != nil {
		tmpID = *d.ID
	}
	var tmpName string
	if d.Name != nil {
		tmpName = *d.Name
	}
	var tmpMotherCompanyID *int
	if d.MotherCompanyID != nil {
		tmpMotherCompanyID = d.MotherCompanyID
	}
	var tmpMotherCompany Company
	if d.MotherCompany != nil {
		tmpMotherCompany = d.MotherCompany.MergeToType()
	}
	return Company{
		ID:              tmpID,
		Name:            tmpName,
		MotherCompanyID: tmpMotherCompanyID,
		MotherCompany:   &tmpMotherCompany,
	}
}

func (d *CompanyInput) MergeToType() Company {

	tmpID := d.ID

	tmpName := d.Name

	var tmpMotherCompanyID *int
	if d.MotherCompanyID != nil {
		tmpMotherCompanyID = d.MotherCompanyID
	}
	var tmpMotherCompany Company
	if d.MotherCompany != nil {
		tmpMotherCompany = d.MotherCompany.MergeToType()
	}
	return Company{
		ID:              tmpID,
		Name:            tmpName,
		MotherCompanyID: tmpMotherCompanyID,
		MotherCompany:   &tmpMotherCompany,
	}
}

func (d *UserPatch) MergeToType() User {
	var tmpID int
	if d.ID != nil {
		tmpID = *d.ID
	}
	var tmpName string
	if d.Name != nil {
		tmpName = *d.Name
	}
	var tmpCompanyID *int
	if d.CompanyID != nil {
		tmpCompanyID = d.CompanyID
	}
	var tmpCompany Company
	if d.Company != nil {
		tmpCompany = d.Company.MergeToType()
	}
	return User{
		ID:        tmpID,
		Name:      tmpName,
		CompanyID: tmpCompanyID,
		Company:   &tmpCompany,
	}
}

func (d *UserInput) MergeToType() User {

	tmpID := d.ID

	tmpName := d.Name

	var tmpCompanyID *int
	if d.CompanyID != nil {
		tmpCompanyID = d.CompanyID
	}
	var tmpCompany Company
	if d.Company != nil {
		tmpCompany = d.Company.MergeToType()
	}
	return User{
		ID:        tmpID,
		Name:      tmpName,
		CompanyID: tmpCompanyID,
		Company:   &tmpCompany,
	}
}
